name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    # permissions:
    #   contents: read
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Setup runtime environment
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.4.8
          cabal-version: 3.10.3.0

      - name: Update package manager
        run: cabal update

      - name: Install dependencies
        run: cabal build --dependencies-only --enable-documentation

      - name: Build artifact
        run: cabal haddock --haddock-options="--odir=build/" --haddock-for-hackage --enable-documentation --haddock-hyperlink-source

      - name: Upload Haddock artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: _site/

      - name: Prepare deployment
        uses: actions/upload-pages-artifact@v2

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v2
